---

- import_playbook: tasks/api-microservice-list.yml

- hosts: server
  vars_prompt:
    - name: microservice
      prompt: "microservice name please "
      private: False
      when: microservice == undefined
  vars:
    body:
      token: "{{ wiseflat_user_token }}"
      label: "{{ microservice }}"
  tasks:

    - name: Clean up
      file:
        path: /tmp/{{ microservice }}.tar.gz
        state: absent

    - name: Download microservice
      command: curl -X POST -d "token={{ wiseflat_user_token }}" -d "label={{ microservice }}" https://api.wiseflat.com/microservice/download -o /tmp/{{ microservice }}.tar.gz

    - name: Delete old lxc image if exists
      command: /snap/bin/lxc image delete {{ microservice }}
      ignore_errors: True

    - name: Import microservice to lxd image store
      command: /snap/bin/lxc image import /tmp/{{ microservice }}.tar.gz --alias {{ microservice }}
      ignore_errors: True

    - name: Clean up
      file:
        path: /tmp/{{ microservice }}.tar.gz
        state: absent

    - name: Create microservice
      command: /snap/bin/lxc init {{ microservice }} home-{{ microservice }}
      # ignore_errors: True

    - name: Start microservice
      command: /snap/bin/lxc start home-{{ microservice }}
      # ignore_errors: True

    - name: Copy your authorized_keys to home-{{ microservice }}
      command: lxc file push ~/.ssh/authorized_keys home-{{ microservice }}/home/ubuntu/.ssh/authorized_keys