---

- hosts: server
  tasks:

    # common tasks

    - name: Set timezone
      become: true
      timezone:
        name: "{{ common_timezone }}"

    - name: Update sources.list
      become: true
      replace:
        path: /etc/apt/sources.list
        regexp: '#deb-src'
        replace: 'deb-src'

    - name: Remove unused packages
      become: true
      apt: 
        name: "{{ item }}"
        state: absent
      with_items: "{{ common_package_to_remove }}"

    - name: Install useful packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      with_items: "{{ common_package_to_install }}"

    # - name: Adjust APT update intervals
    #   copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

    # pc network

    - name: Configure network interface
      become: true
      template:
        src: network/interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644

    # lxd tasks

    - name: Install lxd via snap
      become: true
      command: snap install lxd
      # no_log: True

    # - name: You need to intall lxc with snap manually... It doesn't with ansible. I don't know why yet
    #   pause:

    

    - name: Sleep for 60 seconds until snapd started correctly
      wait_for: timeout=60
      delegate_to: localhost

    - name: Append the group 'lxd' to the user pi
      become: true
      user:
        name: pi
        groups: lxd
        append: yes

    - include_tasks: tasks/noreboot.yml

    - name: Init LXD daemon
      command: '/snap/bin/lxd init --auto --network-address {{ lxd_daemon_network_adress }} --network-port {{ lxd_daemon_port }} --trust-password {{ lxd_trust_password }}'

    - name: Add local daemon as a remote server
      command: /snap/bin/lxc remote add {{ ansible_hostname }} 127.0.0.1 --password={{ lxd_trust_password }} --accept-certificate=true 
      ignore_errors: True

    - name: Update default lxd profile
      tags: lxd_profile
      lxd_profile:
        name: default
        state: present
        cert_file: "/home/{{ansible_ssh_user}}/snap/lxd/current/.config/lxc/client.crt"
        key_file: "/home/{{ansible_ssh_user}}/snap/lxd/current/.config/lxc/client.key"
        url: "https://127.0.0.1:8443"
        description: default profile
        devices:
          root:
            path: /
            pool: default
            type: disk
          eth0:
            nictype: macvlan
            parent: br0
            type: nic
