---

- hosts: localhost
  vars:
    body:
      token: "{{ wiseflat_user_token }}"
      cron: "{{ wiseflat_api_cron }}"
  tasks:

    - name: post personnal information
      uri:
        url: "https://api.wiseflat.com/cron/update"
        validate_certs: False
        method: POST
        body: ' {{ body | to_json}}'
        body_format: json
      register: result

    - debug:
        msg: "{{ result.json }}"