---

- hosts: server
  gather_facts: yes
  vars:
    body:
      token: "{{ wiseflat_user_token }}"

  tasks:

    - uri:
        url: https://api.wiseflat.com/user/info
        validate_certs: False
        method: POST
        body: ' {{ body | to_json}}'
        body_format: json
      register: result

    - debug:
        msg: "{{ result.json }}"