---

- hosts: server
  vars:
    body:
      token: "{{ wiseflat_user_token }}"
      firstname: "{{ wiseflat_user_firstname }}"
      lastname: "{{ wiseflat_user_lastname }}"
      email: "{{ wiseflat_user_email }}"
      label: "{{ wiseflat_user_label }}"
  tasks:

    - uri:
        url: https://api.wiseflat.com/user/update
        validate_certs: False
        method: POST
        body: ' {{ body | to_json}}'
        body_format: json
      register: result

    - debug:
        msg: "{{ result.json }}"