---
- hosts: server
  vars:
    body:
      token: "{{ wiseflat_user_token }}"
      status: "{{ wiseflat_heartbeat_status }}"
  tasks:
    - name: post personnal information
      uri:
        url: https://api.wiseflat.com/heartbeat/update
        validate_certs: False
        method: POST
        body: ' {{ body | to_json}}'
        body_format: json
      register: result
    - debug:
        msg: "{{ result.json }}"

    - name: "add or update heartbeat crontab"
      cron:
        name: "heartbeat cron"
        minute: "*"
        day: "*"
        hour: "*"
        state: present
        job: 'curl -s -X POST -d "token={{ wiseflat_user_token }}" -d "status=1" https://api.wiseflat.com/heartbeat/update 1>/dev/null 2>&1'
      when: wiseflat_heartbeat_status == '1'

    - name: "add or update heartbeat crontab"
      cron:
        name: "heartbeat cron"
        minute: "*"
        day: "*"
        hour: "*"
        state: absent
        job: 'curl -s -X POST -d "token={{ wiseflat_user_token }}" -d "status=1" https://api.wiseflat.com/heartbeat/update 1>/dev/null 2>&1'
      when: wiseflat_heartbeat_status == '0'