---

- block:

    - name: Check if a reboot is required
      register: file
      stat: path=/home/{{ ansible_ssh_user }}/.noreboot get_md5=no

    - name: Create noreboot file
      file:
        path: /home/{{ ansible_ssh_user }}/.noreboot
        state: touch
      when: file.stat.exists is defined and file.stat.exists == false

    - name: Reboot
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      become: true
      async: 1
      poll: 0
      ignore_errors: true
      when: file.stat.exists is defined and file.stat.exists == false

    - name: sleep for 60 seconds
      wait_for: timeout=60
      delegate_to: localhost
      when: file.stat.exists is defined and file.stat.exists == false

    - name: Be sure your raspberry pi is available before continue
      pause:
      when: file.stat.exists is defined and file.stat.exists == false
